### ISSUE TITLE
Moodle source and data directories are hardcoded in build process

### ISSUE THREAD

**Issue by martignoni** [martignoni/moodlebox#49]
We have to move hardcoded `/var/www/moodle` installation directory to an ansible variable. Same for `/var/www/moodledata`.

**Comment by martignoni** [comment]
See commit 4c97212.

**Comment by ralf-krause** [comment]
Hi Nicolas, 
as I know you will need a static url for Moodle. A lot of links for pictures and other resources are completely saved in the database. If you change the url of a Moodle platform you must replace all of these saved entries with a script. http://moodlebox.home/admin/tool/replace/
Best regards, Ralf

**Comment by martignoni** [comment]
Thanks Ralf. This issue is about replacing the hardcoded values or the source and data directories in the building flow of the moodlebox (not replacing anything once the MoodleBox is installed. 

As you can see in commit 4c97212 , this is already done.

**Comment by martignoni** [comment]
Tested, closing.
