### ISSUE TITLE
Adapt motd to display pertinent info

### ISSUE THREAD

**Issue by martignoni** [martignoni/moodlebox#51]
At login, motd should display info about MoodleBox version, author and copyright.

**Comment by martignoni** [comment]
Very interesting resource about customizing `motd`: https://ownyourbits.com/2017/04/05/customize-your-motd-login-message-in-debian-and-ubuntu/.

**Comment by martignoni** [comment]
See also: https://github.com/hopey-dishwasher/termpix

**Comment by martignoni** [comment]
Fixed by 1d20bd0 and b784484. Closing.

**Comment by ralf-krause** [comment]
I found that the logo doesn't look fine in my iPad Terminus app.
![moodlebox-login](https://user-images.githubusercontent.com/27956839/36077057-12067770-0f66-11e8-960e-5bd4bb5b6a05.jpg)

**Comment by martignoni** [comment]
Indeed. Would you please send me the link to your terminal app?

**Comment by ralf-krause** [comment]
Termius von Crystalnix
https://itunes.apple.com/de/app/termius/id549039908?mt=8

**Comment by ralf-krause** [comment]
Hi Nicolas, I think that Terminus on iOS has problems with the inclused fonts. I tested Terminus on Android and the font PTmono shows the correct moodlebox logo. Ralf 
![145a519a-92bc-457c-9098-21ffd1c933df](https://user-images.githubusercontent.com/27956839/38171257-6b44856a-3596-11e8-9f7e-cf3f86f08652.jpeg)

**Comment by ralf-krause** [comment]
Hi Nicolas,
since today the Termius app for iOS shows the MoodleBox logo correctly. The Termius app is updated for iPhone and iPad. The app is free.
Ralf

![img_3943](https://user-images.githubusercontent.com/27956839/42578101-1f8ede6a-8526-11e8-9c1a-94ba7054ff91.jpeg)
