### ISSUE TITLE
Raspbian version incorrect in About page of moodlebox.net page

### ISSUE THREAD

**Issue by ratnavis** [martignoni/moodlebox#56]
The https://www.raspberrypi.org/downloads/raspbian/ used to offer Wheezy, then Jessie and now Stretch. This collides with the MoodleBox instructions. For example https://github.com/martignoni/moodlebox.net/blob/master/en/_pages/about.md says "MoodleBox is built around a Raspberry Pi 3 and the Raspbian Jessie Lite distro." but the hyperlink on "Raspbian Jessie Lite" now offers Stretch.

**Comment by martignoni** [comment]
Thanks. Fixed.

**Comment by martignoni** [comment]
See https://github.com/martignoni/moodlebox.net/commit/c291b142702bd41b7072d7c7c1f226f8bf5b753c.
